import Head from "next/head";
import LandingPage from "@/Components/LandingPage";

export default function Home(props:any) {
  return (
    <>
      <Head>
        <title>Advice Generator app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage advice={props.data} />
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts/1`);
  const adv:adv[] = await res.json();
  return {
    props: {
      advice: adv,
    },
  };
};
